# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: 2017
title-normal: UC Davis Plant Science Symposium
email: gmunjal@ucdavis.edu
description: ""
baseurl: "/2017/" # the subpath of your site, e.g. /blog
url: "http://pbgso.github.io/" # the base hostname & protocol for your site
author: Gitanshu Munjal
street_address: UC Davis Conference Center
city: Davis
state: CA
zip_code: 95616
country: United States of America
phone: 

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages" 
tiles-count: 4

# Social settings
500px_url: 
facebook_url: 

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username:
# Add one or more of the following
facebook:
  app_id: 
  publisher: 
  admins: 
logo:
google_site_verification: 
